# Generated by Django 2.2.4 on 2019-10-04 04:14

from django.db import migrations, models
import django.db.models.deletion
import extra_app.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('browserNum', models.IntegerField()),
                ('articleStatus', models.IntegerField()),
                ('heading', models.CharField(max_length=250)),
                ('thumb', models.CharField(max_length=250)),
                ('modifydate', models.DateTimeField(auto_now=True)),
                ('adminId', models.ForeignKey(on_delete=None, to='server.admin')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menuId', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=200)),
                ('menuStatus', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('positionId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='position_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionId', models.IntegerField()),
                ('articleId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='source',
            fields=[
                ('sourceId', models.AutoField(primary_key=True, serialize=False)),
                ('sourceName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='articlecontent',
            fields=[
                ('contentId', models.AutoField(primary_key=True, serialize=False)),
                ('contents', extra_app.DjangoUeditor.models.UEditorField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='menuId',
            field=models.ForeignKey(on_delete=None, to='server.menu'),
        ),
        migrations.AddField(
            model_name='article',
            name='sourceId',
            field=models.ForeignKey(on_delete=None, to='server.source'),
        ),
    ]
