# Generated by Django 2.2.4 on 2019-10-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20191004_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='adminId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='browserNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='menuId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='sourceId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.CharField(default='compass.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='articleId',
            field=models.IntegerField(),
        ),
    ]
