# Generated by Django 2.2.4 on 2019-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=50)),
            ],
        ),
    ]
