# Generated by Django 2.2.4 on 2019-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191005_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
