# Generated by Django 2.2.4 on 2019-10-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_position_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
