# Generated by Django 2.2.4 on 2019-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20191005_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='positionStatus',
            field=models.IntegerField(default=0),
        ),
    ]
