# Generated by Django 2.2.4 on 2019-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20190929_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='topics',
        ),
        migrations.AddField(
            model_name='menu',
            name='menuStatus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
