# Generated by Django 2.2.4 on 2019-10-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_position_positionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='headingColor',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
