# Generated by Django 2.2.4 on 2019-10-05 08:39

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_article_headingcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='introduction',
            field=DjangoUeditor.models.UEditorField(null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='loginTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
