# Generated by Django 2.2.4 on 2019-10-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20191005_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='headImg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
